# Site settings

title:          Lataman

description:    "Lataman likes cheese"

baseurl:        "/lataman"

url:            "https://Lataman.github.io"



# Google Analytics

google_analytics: UA—XXXXXXXX-X



# Author

author:

  name:         Hai Kwon
  email:        haiar@gmail.com



# Build settings

markdown:       kramdown

include:

  - _pages



# Assets

sass:

  sass_dir:     _sass

  style:        compressed



# Gems

plugins:

  - jekyll-feed

  - jekyll-paginate

  - jekyll-seo-tag

  # - jemoji #Uncomment this to allow emoji in your post



# Permalinks

permalink:      /:year-:month-:day/:title

paginate:       5



# Excludes

exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
